/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PolitikaKolacicaRouteImport } from './routes/politika-kolacica'
import { Route as PolitikaPrivatnostiRouteImport } from './routes/politika-privatnosti'
import { Route as PravnoObavestenjeRouteImport } from './routes/pravno-obavestenje'
import { Route as PricaRouteImport } from './routes/prica'
import { Route as ProizvodiRouteImport } from './routes/proizvodi'
import { Route as UsloviKoriscenjaRouteImport } from './routes/uslovi-koriscenja'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaKolacicaRoute = PolitikaKolacicaRouteImport.update({
  id: '/politika-kolacica',
  path: '/politika-kolacica',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaPrivatnostiRoute = PolitikaPrivatnostiRouteImport.update({
  id: '/politika-privatnosti',
  path: '/politika-privatnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const PravnoObavestenjeRoute = PravnoObavestenjeRouteImport.update({
  id: '/pravno-obavestenje',
  path: '/pravno-obavestenje',
  getParentRoute: () => rootRouteImport,
} as any)
const PricaRoute = PricaRouteImport.update({
  id: '/prica',
  path: '/prica',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodiRoute = ProizvodiRouteImport.update({
  id: '/proizvodi',
  path: '/proizvodi',
  getParentRoute: () => rootRouteImport,
} as any)
const UsloviKoriscenjaRoute = UsloviKoriscenjaRouteImport.update({
  id: '/uslovi-koriscenja',
  path: '/uslovi-koriscenja',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/politika-kolacica': typeof PolitikaKolacicaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/pravno-obavestenje': typeof PravnoObavestenjeRoute
  '/prica': typeof PricaRoute
  '/proizvodi': typeof ProizvodiRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/politika-kolacica': typeof PolitikaKolacicaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/pravno-obavestenje': typeof PravnoObavestenjeRoute
  '/prica': typeof PricaRoute
  '/proizvodi': typeof ProizvodiRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/politika-kolacica': typeof PolitikaKolacicaRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/pravno-obavestenje': typeof PravnoObavestenjeRoute
  '/prica': typeof PricaRoute
  '/proizvodi': typeof ProizvodiRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impressum'
    | '/kontakt'
    | '/politika-kolacica'
    | '/politika-privatnosti'
    | '/pravno-obavestenje'
    | '/prica'
    | '/proizvodi'
    | '/uslovi-koriscenja'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impressum'
    | '/kontakt'
    | '/politika-kolacica'
    | '/politika-privatnosti'
    | '/pravno-obavestenje'
    | '/prica'
    | '/proizvodi'
    | '/uslovi-koriscenja'
  id:
    | '__root__'
    | '/'
    | '/impressum'
    | '/kontakt'
    | '/politika-kolacica'
    | '/politika-privatnosti'
    | '/pravno-obavestenje'
    | '/prica'
    | '/proizvodi'
    | '/uslovi-koriscenja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PolitikaKolacicaRoute: typeof PolitikaKolacicaRoute
  PolitikaPrivatnostiRoute: typeof PolitikaPrivatnostiRoute
  PravnoObavestenjeRoute: typeof PravnoObavestenjeRoute
  PricaRoute: typeof PricaRoute
  ProizvodiRoute: typeof ProizvodiRoute
  UsloviKoriscenjaRoute: typeof UsloviKoriscenjaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-kolacica': {
      id: '/politika-kolacica'
      path: '/politika-kolacica'
      fullPath: '/politika-kolacica'
      preLoaderRoute: typeof PolitikaKolacicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-privatnosti': {
      id: '/politika-privatnosti'
      path: '/politika-privatnosti'
      fullPath: '/politika-privatnosti'
      preLoaderRoute: typeof PolitikaPrivatnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravno-obavestenje': {
      id: '/pravno-obavestenje'
      path: '/pravno-obavestenje'
      fullPath: '/pravno-obavestenje'
      preLoaderRoute: typeof PravnoObavestenjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prica': {
      id: '/prica'
      path: '/prica'
      fullPath: '/prica'
      preLoaderRoute: typeof PricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodi': {
      id: '/proizvodi'
      path: '/proizvodi'
      fullPath: '/proizvodi'
      preLoaderRoute: typeof ProizvodiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslovi-koriscenja': {
      id: '/uslovi-koriscenja'
      path: '/uslovi-koriscenja'
      fullPath: '/uslovi-koriscenja'
      preLoaderRoute: typeof UsloviKoriscenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PolitikaKolacicaRoute: PolitikaKolacicaRoute,
  PolitikaPrivatnostiRoute: PolitikaPrivatnostiRoute,
  PravnoObavestenjeRoute: PravnoObavestenjeRoute,
  PricaRoute: PricaRoute,
  ProizvodiRoute: ProizvodiRoute,
  UsloviKoriscenjaRoute: UsloviKoriscenjaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
