/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PricaRouteImport } from './routes/prica'
import { Route as ProizvodiRouteImport } from './routes/proizvodi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricaRoute = PricaRouteImport.update({
  id: '/prica',
  path: '/prica',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodiRoute = ProizvodiRouteImport.update({
  id: '/proizvodi',
  path: '/proizvodi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/prica': typeof PricaRoute
  '/proizvodi': typeof ProizvodiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/prica': typeof PricaRoute
  '/proizvodi': typeof ProizvodiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/prica': typeof PricaRoute
  '/proizvodi': typeof ProizvodiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/prica' | '/proizvodi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/prica' | '/proizvodi'
  id: '__root__' | '/' | '/kontakt' | '/prica' | '/proizvodi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  PricaRoute: typeof PricaRoute
  ProizvodiRoute: typeof ProizvodiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prica': {
      id: '/prica'
      path: '/prica'
      fullPath: '/prica'
      preLoaderRoute: typeof PricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodi': {
      id: '/proizvodi'
      path: '/proizvodi'
      fullPath: '/proizvodi'
      preLoaderRoute: typeof ProizvodiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  PricaRoute: PricaRoute,
  ProizvodiRoute: ProizvodiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
